addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      # Package list from http://bazel.io/docs/install.html
      - pkg-config
      - zip
      - unzip
      - zlib1g-dev
jdk:
  - oraclejdk8

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.2.2b/bazel-0.2.2b-installer-linux-x86_64.sh'
  - '[[ "$(sha256sum <bazel-0.2.2b-installer-linux-x86_64.sh)" == "4b45fbafe3376e3a6016641f8d2169a581272d93d81b736f33daeb21a4105df0  -" ]]'
  - chmod +x bazel-0.2.2b-installer-linux-x86_64.sh
  - ./bazel-0.2.2b-installer-linux-x86_64.sh --user

script:
  - bazel --batch --host_jvm_args=-Xmx1000m --host_jvm_args=-Xms1000m test closure/... --verbose_failures --test_output=errors --test_strategy=standalone --spawn_strategy=standalone --genrule_strategy=standalone --local_resources=1000,1,1.0
