addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - wget
      # Package list from http://bazel.io/docs/install.html
      - pkg-config
      - zip
      - unzip
      - zlib1g-dev

jdk:
  - oraclejdk8

env:
  - V=HEAD URL=http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastSuccessfulBuild/artifact/output/ci/bazel--installer.sh FLAGS='--worker_verbose --strategy=Javac=worker --strategy=JsChecker=worker'
  - V=0.3.0 URL=http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/bazel/releases/download/0.3.0/bazel-0.3.0-installer-linux-x86_64.sh FLAGS=''
  - V=0.2.2b URL=http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/bazel/releases/download/0.2.2b/bazel-0.2.2b-installer-linux-x86_64.sh FLAGS=''

before_install:
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx1000m \
      --host_jvm_args=-Xms1000m \
      test \
      closure/... \
      --verbose_failures \
      --test_output=errors \
      --test_strategy=standalone \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=1000,1,1.0 \
      $FLAGS

notifications:
  email: false
